version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-egames
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi-contrase√±a
      MYSQL_DATABASE: egames
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/mysql/1egames.sql:/docker-entrypoint-initdb.d/1egames.sql"
      - "./docker/mysql/2egamesInsertData.sql:/docker-entrypoint-initdb.d/2egamesInsertData.sql"
      - "./docker/mysql/3egamesStockData.sql:/docker-entrypoint-initdb.d/3egamesStockData.sql"
      - ~/hyruleShopData/mysql:/var/lib/mysql
    networks:
      - egames
  node:
    build: ./back
    container_name: node-egames
    restart: always
    environment:
      - VIRTUAL_HOST=api.hyruleshop.jesuscabado.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.hyruleshop.jesuscabado.com
      - LETSENCRYPT_EMAIL=admin@jesuscabado.com
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - egames
      - proxy
    volumes:
      - ./back:/usr/src/app
      - exclude:/usr/src/app/node_modules/
  react:
    image: nginx:alpine
    container_name: react-egames
    restart: always
    environment:
      - VIRTUAL_HOST=hyruleshop.jesuscabado.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=hyruleshop.jesuscabado.com
      - LETSENCRYPT_EMAIL=admin@jesuscabado.com
    expose:
      - 80
    depends_on:
      - node
    networks:
      - egames
      - proxy
    volumes:
      - /home/ubuntu/hyruleshop:/usr/share/nginx/html:ro
volumes:
  exclude:
networks:
  egames:
  proxy:
    name: nginx-proxy
    external: true
